"""Generates database/seed.sql (demo data). Run from the backend folder:
    python scripts/generate_seed.py

The output is deterministic (same file every run) and uses dates RELATIVE to the day the
seed is loaded (CURRENT_DATE - n), so the history always looks recent.
Demo passwords: staff = Steg2026!   citizens = Citizen2026!
"""
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from auth import hash_password  # noqa: E402

random.seed(2026)
OUT = Path(__file__).resolve().parents[2] / "database" / "seed.sql"

# (bcc name, region, avg load MW, governorate, [(zone, lat, lon), ...])
NETWORK = [
    ("BCC Tunis", "nord", 420, "Tunis", [("Menzah", 36.8420, 10.1680), ("Bardo", 36.8092, 10.1344), ("Ras Tabia", 36.8146, 10.1560)]),
    ("BCC Ariana", "nord", 260, "Ariana", [("Ariana Ville", 36.8601, 10.1934), ("Ettadhamen", 36.8386, 10.1025), ("La Soukra", 36.8742, 10.2208)]),
    ("BCC Bizerte", "nord", 180, "Bizerte", [("Bizerte Nord", 37.2744, 9.8739), ("Menzel Bourguiba", 37.1537, 9.7856), ("Mateur", 37.0400, 9.6650)]),
    ("BCC Nabeul", "nord", 210, "Nabeul", [("Nabeul Ville", 36.4561, 10.7376), ("Hammamet", 36.4000, 10.6167), ("Kelibia", 36.8475, 11.0939)]),
    ("BCC Sfax", "sud", 380, "Sfax", [("Sfax Centre", 34.7406, 10.7603), ("Sakiet Ezzit", 34.8000, 10.7400), ("Sakiet Eddaier", 34.8000, 10.8300), ("El Ain", 34.7300, 10.6900), ("Gremda", 34.7600, 10.7900)]),
    ("BCC Gabes", "sud", 190, "Gabes", [("Gabes Ville", 33.8815, 10.0982), ("Gabes Ouest", 33.8850, 10.0600)]),
    ("BCC Medenine", "sud", 150, "Medenine", [("Medenine Centre", 33.3549, 10.5055), ("Houmt Souk", 33.8756, 10.8575)]),
]

# Critical sites: priority 0, never cut (hospitals, water pumping)
CRITICAL = {"Ras Tabia": "Depart_RasTabia_Hopital", "Sfax Centre": "Depart_SfaxCentre_CHU",
            "Gabes Ville": "Depart_GabesVille_Hopital", "Bizerte Nord": "Depart_BizerteNord_Hopital",
            "La Soukra": "Depart_LaSoukra_PompageSONEDE"}

HIGH_DEMAND = {"Sakiet Eddaier"}
CUT_HOURS = [(18, 0), (18, 45), (19, 30), (20, 15), (13, 0), (14, 0)]  # typical peak slots

lines = ["-- ============================================================",
         "-- ENERGY BALANCE TN - DEMO SEED DATA (generated by backend/scripts/generate_seed.py)",
         "-- Load AFTER schema.sql. Dates are relative to the day it is loaded.",
         "-- Demo passwords: staff = Steg2026!   citizens = Citizen2026!",
         "-- ============================================================", "",
         "INSERT INTO regions (name, code, target_ratio) VALUES",
         "    ('North', 'nord', 0.6600),", "    ('South', 'sud', 0.3400);", ""]

bcc_rows, zone_rows, feeders = [], [], []
zone_id = 0
for bcc_idx, (bcc_name, region, load, gov, zones) in enumerate(NETWORK, start=1):
    bcc_rows.append(f"    ('{bcc_name}', {load:.2f}, '{region}')")
    for zname, lat, lon in zones:
        zone_id += 1
        status = "High Demand" if zname in HIGH_DEMAND else "Power Available"
        zone_rows.append(f"    ('{zname}', '{gov}', {lat}, {lon}, '{status}')")
        tag = zname.replace(" ", "")
        n = random.choice([2, 2, 3])
        if zname in CRITICAL:
            feeders.append({"name": CRITICAL[zname], "bcc": bcc_idx, "zone": zone_id, "prio": 0,
                            "load": round(random.uniform(1.5, 4.0), 2), "region": region})
        for k in range(1, n + 1):
            feeders.append({"name": f"Depart_{tag}_{k}", "bcc": bcc_idx, "zone": zone_id,
                            "prio": random.choices([1, 2, 3, 4, 5], weights=[10, 20, 30, 25, 15])[0],
                            "load": round(random.uniform(2.0, 9.0), 2), "region": region})

lines += ["INSERT INTO bcc (name, avg_load_mw, crc) VALUES", ",\n".join(bcc_rows) + ";", ""]
lines += ["INSERT INTO zones (name, governorate, latitude, longitude, electricity_status) VALUES",
          ",\n".join(zone_rows) + ";", ""]

# ---- 30 days of history: executed cuts. The South was cut a bit more often (realistic demo). ----
schedules = []  # (feeder_index, days_ago, h, m)
for i, f in enumerate(feeders):
    if f["prio"] == 0:
        continue
    extra = 1 if f["region"] == "sud" else 0
    n_cuts = random.choices([0, 1, 2, 3, 4], weights=[25, 30, 25, 12, 8])[0] + (extra if random.random() < 0.5 else 0)
    days = sorted(random.sample(range(1, 29), n_cuts), reverse=True)
    for d in days:
        h, m = random.choice(CUT_HOURS)
        schedules.append((i, d, h, m))
    if days:
        f["last_days"], f["last_h"], f["last_m"] = days[-1], *[x for x in schedules[-1][2:]]
    f["cuts"] = n_cuts

feeder_rows = []
for f in feeders:
    last = (f"(CURRENT_DATE - {f['last_days']}) + TIME '{f['last_h']:02d}:{f['last_m']:02d}'"
            if f.get("cuts") else "NULL")
    feeder_rows.append(f"    ('{f['name']}', {f['bcc']}, {f['zone']}, {f['prio']}, {f['load']:.2f}, "
                       f"{last}, {f.get('cuts', 0)}, TRUE)")
lines += ["INSERT INTO feeders (name, bcc_id, zone_id, priority_level, avg_load_mw, last_cut_at, total_cuts_month, active) VALUES",
          ",\n".join(feeder_rows) + ";", ""]

sched_rows, exec_rows = [], []
for sid, (i, d, h, m) in enumerate(schedules, start=1):
    f = feeders[i]
    end_total = h * 60 + m + 45
    start_t, end_t = f"{h:02d}:{m:02d}", f"{end_total // 60:02d}:{end_total % 60:02d}"
    sched_rows.append(f"    ({i + 1}, {f['zone']}, CURRENT_DATE - {d}, '{start_t}', '{end_t}', 45, {f['load']:.2f}, "
                      f"'executed', 'Priority {f['prio']}/5, rotation')")
    shed = round(f["load"] * random.uniform(0.9, 1.0), 2)
    exec_rows.append(f"    ({sid}, (CURRENT_DATE - {d}) + TIME '{start_t}', (CURRENT_DATE - {d}) + TIME '{end_t}', {shed:.2f}, NULL)")
lines += ["INSERT INTO program_schedule (feeder_id, zone_id, scheduled_date, start_time, end_time, duration_minutes, target_mw, status, reason) VALUES",
          ",\n".join(sched_rows) + ";", ""]
lines += ["INSERT INTO execution_log (schedule_id, actual_start, actual_end, actual_mw_shed, notes) VALUES",
          ",\n".join(exec_rows) + ";", ""]

# ---- J-1 data for tomorrow: 48 half-hour slots, deficit in the evening peak ----
load_rows = []
for slot in range(48):
    hour = slot / 2
    load = 2900 + 900 * max(0.0, 1 - abs(hour - 20) / 5) + 300 * max(0.0, 1 - abs(hour - 13) / 4)
    available = 3500
    load_rows.append(f"    (CURRENT_DATE + 1, {slot}, 30, {load:.2f}, {available:.2f})")
lines += ["INSERT INTO load_resource_data (target_date, slot_index, time_step_minutes, load_mw, available_mw) VALUES",
          ",\n".join(load_rows) + ";", "",
          "INSERT INTO national_targets (target_date, target_mw) VALUES (CURRENT_DATE + 1, 300.00);", ""]

# ---- demo accounts ----
staff = [("Admin STEG", "admin@steg.tn", "admin", None), ("Dispatching National", "dn@steg.tn", "dn", None),
         ("CRC Nord", "crc.nord@steg.tn", "crc_nord", None), ("CRC Sud", "crc.sud@steg.tn", "crc_sud", None),
         ("Operateur BCC Tunis", "bcc.tunis@steg.tn", "bcc", 1), ("Operateur BCC Sfax 1", "bcc.sfax@steg.tn", "bcc", 5),
         ("Operateur BCC Sfax 2", "bcc.sfax2@steg.tn", "bcc", 5)]
staff_rows = [f"    ('{n}', '{e}', '{hash_password('Steg2026!')}', '{r}', {b if b else 'NULL'})" for n, e, r, b in staff]
lines += ["INSERT INTO staff_users (full_name, email, password_hash, role, bcc_id) VALUES",
          ",\n".join(staff_rows) + ";", ""]

zone_ids = {z[0]: idx for idx, z in enumerate([z for net in NETWORK for z in net[4]], start=1)}
citizens = [("Mohamed", "Ghazi", "mohamed.ghazi@example.com", "Sfax Centre", "Sfax"),
            ("Idriss", "Driss", "idriss@example.com", "Menzah", "Tunis"),
            ("Amina", "Ben Salah", "amina@example.com", "Gabes Ville", "Gabes")]
cit_rows = [f"    ('{fn}', '{ln}', '{e}', '+21600000000', '{hash_password('Citizen2026!')}', {zone_ids[z]}, '{g}')"
            for fn, ln, e, z, g in citizens]
lines += ["INSERT INTO citizens (first_name, last_name, email, phone, password_hash, zone_id, governorate) VALUES",
          ",\n".join(cit_rows) + ";", ""]

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUT}: {len(NETWORK)} BCCs, {zone_id} zones, {len(feeders)} feeders, "
      f"{len(schedules)} past cuts, {len(staff)} staff, {len(citizens)} citizens")
