"""add_auto_mode_to_bccs

Revision ID: a3388528cdb8
Revises: cec95ac7c838
Create Date: 2026-09-29 19:11:06.739224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3388528cdb8'
down_revision: Union[str, None] = 'cec95ac7c838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with a server_default so existing rows get FALSE immediately,
    # then remove the server_default so future inserts use the model default.
    op.add_column('bccs', sa.Column(
        'auto_mode', sa.Boolean(), nullable=False, server_default=sa.false()
    ))
    op.alter_column('bccs', 'auto_mode', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bccs', 'auto_mode')
    # ### end Alembic commands ###
