"""add_feeder_refs_to_programme_slots

Revision ID: cec95ac7c838
Revises: d11af2a89ed3
Create Date: 2026-09-29 17:39:39.888529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec95ac7c838'
down_revision: Union[str, None] = 'd11af2a89ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programme_slots', sa.Column('feeder_refs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programme_slots', 'feeder_refs')
    # ### end Alembic commands ###
